### PR TITLE
All binaries to folder bin

### PR DESCRIPTION
**Pull request by gcarreno**
This redirects all binaries to a folder bin that is present at the root of the repository.

Also changed `.gitignore` to ignore it.

### CODE REVIEW

**Comment by MWASoftware** [comment]
Firstly, I am not sure why this is important.

Looking at the affected files. It is better to delete the .ico files. These are just Lazarus placeholder images and can be safely removed. The only exception is a single .png file that is the source for the component palette icon. This could be moved, given that the .lrs (text) file includes it. However, moving it to an "images" folder would be more descriptive and is my preference.

**Comment by gcarreno** [comment]
Hey Tony(@MWASoftware),

The only change that this PR makes is that the compiled units and the executable/binary are dropped into the `bin` folder at the root of the repository. This is a common practice to allow the `.gitignore` file to have a single entry that will ignore all the binaries produced at compile time.

I do not understand why you're talking about images and icons, I 'm now really confused.
The changed files are `*.lpk` and `*.lpi` and the `.gitignore` and you can attest that on the "Files Changed `5`" tab at the top.
Could you please elaborate on the images and icons argument?

Many thanks in advance :)

Cheers,
Gus

**Comment by MWASoftware** [comment]
OK, so I was assuming that you were referring to any binary files in my 
project rather than the result of compilation. The two .ico files and 
the .png file were on the only binary files. Hence my confusion. Isee 
better where you are coming from now.

**Comment by gcarreno** [comment]
Hey Tony(@MWASoftware),

Ok, granted, I did not disambiguate that much and I guess it's a bit my fault that you assumed I wanted to move the binary files that exist on the repo :)

I do hope we're now on the same page !!

Cheers,
Gus

**Comment by MWASoftware** [comment]
Now that (I think that) I have understood what you were driving at, I researched the problem. It looks like there are two solutions around to avoiding "git status" reporting that it needs to add Linux binary files (Windows .exe files are already in the ignore list). One is the solution that you propose with an explicit bin folder, the other is to add the following to the top of .gitignore

# Ignore Linux Binaries
*
!/**/
!*.*

Personally, I prefer this solution as it works with a default Lazarus project config. I have thus preferred this approach. I have also added a general ignore on *.ico files for this project as they are all Lazarus defaults and don't need to be included. 

I also noted that your patch changed the project file to version 12. I am trying to keep with version 11 (and package file version 4) for now. Version 12 comes with Lazarus 2.2 which is only in beta at present. I originally tested the code on a 2.2 snapshot and then did the (Windows) testing on Lazarus 2.0 and immediately tripped over a compatibility issue that forced me to re-create the .lpi and .lpk files for Lazarus 2.0. Hence, I don't want to push out a version 12 lpi file until Lazarus 2.2 is fully released.

**Comment by gcarreno** [comment]
Hey Tony(@MWASoftware),

Thanks for the tip on ignoring Linux binaries, I'll try and use that in the future.

In the case of the `*.ico` file I have one point I wan to get across: When in GNOME and you want an image to use on the `*.desktop` file that will launch your application, it makes sense to leave the `*.ico`.

But that's just my 2c :)

Cheers,
Gus

**Comment by MWASoftware** [comment]
I very much agree with your point about icons. However, what you had made be realise was that I had included Lazarus default icons in the upload to to github - and that was for example programs. These .ico files were just bloat and hence should be excluded. I would suggest that the project specific items in a .gitignore should explicitly list the icons you want to export and ignore the rest.

**Pull request closed without merging**
